config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'ved_dodsfall' => 'pages#ved_dodsfall'
  get 'til_begravelsen' => 'pages#begravelse'
  get 'etter_begravelsen' => 'pages#etter_begravelsen'
  get 'seremoni' => 'pages#seremoni'
  get 'om_oss' => 'pages#om_oss'
  get 'dashboard/index'
  root 'pages#homepage'

  resources :posts
  resources :admin

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/models/obit.rb
class Obit < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :tributes

end

app/models/page.rb
class Page < ApplicationRecord
  has_many :sections
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :page
end

app/models/tribute.rb
class Tribute < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :obit
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/begravelse_helper.rb
module BegravelseHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hjelp_helper.rb
module HjelpHelper
end

app/helpers/obits_helper.rb
module ObitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tributes_helper.rb
module TributesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<div class="booyah-box col-10 offset-1">
  <h2>Log in</h2>

  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="form-inputs">
      <%= f.input :email, required: false, autofocus: true %>
      <%= f.input :password, required: false %>
      <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Log in" %>
    </div>
  <% end %>

  <%= render "devise/shared/links" %>
</div>

app/views/layouts/admin_layout.html.erb
<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Byes</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://use.fontawesome.com/3074d5300d.js"></script>

  </head>

  <body class="push-down">

    <script>
    $(document).ready(function() {






      // breakpoint and up
      $(window).resize(function(){
        if ($(window).width() >= 768){

        // when you hover a toggle show its dropdown menu
        $(".navbar .dropdown-toggle").click(function () {
           $(this).parent().toggleClass("show");
           $(this).parent().find(".dropdown-menu").toggleClass("show");
         });

          // hide the menu when the mouse leaves the dropdown
        $( ".navbar .dropdown-menu" ).mouseleave(function() {
          $(this).removeClass("show");
        });

      // do something here
    }
    });



    // document ready
    });
    </script>

    <% if admin_signed_in? %>
      <header class="push-down">
          <div class="navbar navbar-dark bg-dark fixed-top navbar-small ">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Dashboard', dashboard_index_path, class: 'nav-link' %>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_admin_session_path, method: :delete, class: 'nav-link' %>
              </li>
            </ul>
          </div>
      </header>
    <% end %>

    <div class="top-nav d-flex align-items-center justify-content-center">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Åpen tlf 24/7 - 70 12 12 55', root_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>

  <div class="main-nav container-fluid">
    <nav class="navbar navbar-expand-lg container navbar-light bg-white">

      <div class="logo-holder navbar-brand">
        <%= link_to root_path do %>
          <%= inline_svg "logo.svg", class: 'logo' %>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'Ved dødsfall', ved_dodsfall_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Til begravelsen', til_begravelsen_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Etter begravelsen', etter_begravelsen_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Om oss', om_oss_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Full meny
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

              <div class="container">
                <div class="row">
                  <div class="col-md-3 dropdown-col">
                    <ul class="nav flex-column">
                    <li class="nav-item">
                      <%= link_to 'Ved Dødsfall', ved_dodsfall_path, class: 'nav-link nav-link-title' %>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">I hjemmet</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">På institusjon</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">I utlandet</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Andre årsaker</a>
                    </li>
                  </ul>
                  </div>
                  <!-- /.col-md-4  -->
                  <div class="col-md-3 dropdown-col">
                    <ul class="nav flex-column">
                    <li class="nav-item">
                      <%= link_to 'Til begravelsen', til_begravelsen_path, class: 'nav-link nav-link-title' %>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Seremoni</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Blomster</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Kister</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Urner</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Musikk</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Transport</a>
                    </li>
                  </ul>
                  </div>
                  <!-- /.col-md-4  -->
                  <div class="col-md-3 dropdown-col">
                    <ul class="nav flex-column">
                    <li class="nav-item">
                      <%= link_to 'Etter begravelsen', etter_begravelsen_path, class: 'nav-link nav-link-title' %>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Arv og skifte</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Gravsmonument</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Minnebok</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Urnenedsettelse</a>
                    </li>
                  </ul>
                  </div>
                  <!-- /.col-md-4  -->
                  <div class="col-md-3 dropdown-col">
                    <ul class="nav flex-column">
                    <li class="nav-item">
                      <%= link_to 'Om oss', om_oss_path, class: 'nav-link nav-link-title' %>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Vår historie</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Tilbakemeldinger</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Ansatte</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Priser</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Kontakt</a>
                    </li>
                  </ul>
                  </div>
                  <!-- /.col-md-4  -->
                </div>
              </div>
              <!--  /.container  -->
            </div>
          </li>
        </ul>
      </div>
    </nav>
</div>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>

    <br />
    <br />

    <footer class="footer mid-c">
      <div class="container mid-c">
        <span><%= link_to "® Byes Begravelsesbyrå #{Time.new.year}", root_path, class: 'text-muted' %></span>
      </div>
    </footer>

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Byes</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://use.fontawesome.com/3074d5300d.js"></script>

  </head>

  <body class="push-down">


Hello

<%= yield %>


  </body>



  </html>

app/views/layouts/test.html.erb
<ul class="nav flex column">
  <li class="nav-item"
    <a class="nav-link" href="#">I hjemmet</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">På institusjon</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">I utlandet</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Spesielle omstendigheter</a>
  </li>
</ul>
</div>
<div class="col-3">
Til begravelsen
<ul class="nav flex column">
  <li class="nav-item"
    <a class="nav-link" href="#">Seremoni</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Blomster</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Kister</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Urner</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Musikk</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Transport</a>
  </li>
</ul>
</div>
<div class="col-3">
Etter begravelsen
<ul class="nav flex column">
  <li class="nav-item"
    <a class="nav-link" href="#">Arv og skifterett</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Gravmonument</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Minnebok</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Urnenedsettelse</a>
  </li>
</ul>
</div>
<div class="col-3">
Om oss
<ul class="nav flex column">
  <li class="nav-item"
    <a class="nav-link" href="#">Vår historie</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Tilbakemeldinger</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Våre ansatte</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Priser</a>
  </li>
  <li class="nav-item"
    <a class="nav-link" href="#">Kontakt</a>
  </li>
</ul>

app/views/pages/etter_begravelsen.html.erb
<div class="container-fluid banner-background">
  <div class="container-fluid  main-hero">
    <div class="row full-height etter-begravelsen">
      <div class="col main-col mid-c full-height">
        <div class="box text-center">
          <h1>Etter begravelsen</h1>
          <p>Vi er totalleverandør innen begravelse</p>
          <p>Hos oss vil du bli tatt vare på med respekt og verdighet</p>
          <button class="btn">Se begravelse</button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid" id="begravelse">
    <div class="row">

      <div class="col-sm-12 col-md-6 col-lg-2 offset-1">
        <div class="page-box">
          <h5>Arv og skifterett</h5>
          <div class="info-img">
            <%= image_tag 'church.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main full-width">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-2">
        <div class="page-box">
          <h5>Gravstein</h5>
          <div class="info-img">
            <%= image_tag 'boquet.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main full-width">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-2">
        <div class="page-box">
          <h5>Avdødes digitale liv</h5>
          <div class="info-img">
            <%= image_tag 'church.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main full-width">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-2">
        <div class="page-box">
          <h5>Minnebok</h5>
          <div class="info-img">
            <%= image_tag 'boquet.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main full-width">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-2">
        <div class="page-box">
          <h5>Urnenedsettelse</h5>
          <div class="info-img">
            <%= image_tag 'boquet.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main full-width">Les mer</button>
        </div>
      </div>

    </div>   <!-- row -->

</div>  <!-- container-fluid -->

app/views/pages/homepage.html.erb
<div class="container-fluid banner-background">
  <div class="container-fluid main-hero">
    <div class="row full-height main-banner">
      <div class="col main-col mid-c full-height">
        <div class="main-box text-center">
          <h1>Omsorg ved livets slutt</h1>
          <p>Vi er totalleverandør innen begravelse. Hos oss vil du</p>
          <p> bli tatt vare på med respekt og verdighet</p>
          <%= link_to 'Ta kontakt', om_oss_path, class: 'btn-main' %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

<div class="container section">
  <div class="row">
    <div class="col-sm-12">
      <div class="flower-banner d-flex align-items-center justify-content-end">
        <div class="flower-text ">
          <h1>Kjøp blomster til begravelsen</h1>
          <p>En siste hilsen med blomster kan bety mer enn tusen ord.<p>
          <p>Få blomster sendt direkte til begravelsen eller til hjemmet</p>
          <button class="btn-main btn-banner">Bestill nå</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container-fluid banner-background">
  <div class="container-fluid main-hero">
    <div class="row full-height main-banner">
      <div class="col main-col mid-c full-height">
        <div class="box text-center">
          <h1>Omsorg ved livets slutt</h1>
          <p>Vi er totalleverandør innen begravelse. Hos oss vil du</p>
          <p> bli tatt vare på med respekt og verdighet</p>
          <%= button_to "Ta kontakt", new_message_path, :method => 'get', class: 'btn-main' %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

  <div class="container-fluid" id="begravelse">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-3">
          <div class="page-box">
            <h5>Seremoni</h5>
            <div class="info-img">
              <%= image_tag 'church.jpg', class: 'img-fluid' %>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <button class="btn-main full-width">Les mer</button>
          </div>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-3">
          <div class="page-box">
            <h5>Blomster</h5>
            <div class="info-img">
              <%= image_tag 'boquet.jpg', class: 'img-fluid' %>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <button class="btn-main full-width">Les mer</button>
          </div>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-3">
          <div class="page-box">
            <h5>Seremoni</h5>
            <div class="info-img">
              <%= image_tag 'church.jpg', class: 'img-fluid' %>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <button class="btn-main full-width">Les mer</button>
          </div>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-3">
          <div class="page-box">
            <h5>Blomster</h5>
            <div class="info-img">
              <%= image_tag 'boquet.jpg', class: 'img-fluid' %>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <button class="btn-main full-width">Les mer</button>
          </div>
        </div>

      </div>   <!-- row -->
    </div>  <!-- container -->
  </div>  <!-- container-fluid -->
<br><br><br>
<div class="container-fluid">
  <div class="container section">

    <div class="row">
        <div class="col-sm-12 text-center">
          <h1 class="text-center"><%= link_to 'Minnesider', obits_path, class: 'text-center link' %></h1>
          <br>

        </div>
        <% @obits.limit(4).each do |obit| %>
          <div class="col-sm-12 col-md-3">
            <div>
              <%= link_to obit_path(obit) do %>
                  <%= image_tag obit.image, class: "img-fluid" %>
              <% end %>
            </div>
            <h5 style="margin-top:3px;"><%= "#{obit.f_name} #{obit.l_name}" %></h5>
            <p style="font-size:12px;"><%= "#{obit.birthday} - #{obit.death_date}" %></p>
            <p><%=  %></p>
          </div>
        <% end %>
    </div>
  </div>
</div>

<br>
<br>

  <div class="container section">
    <div class="row">
      <div class="col-sm-12">
        <div class="flower-banner d-flex align-items-center justify-content-end">
          <div class="flower-text ">
            <h1>Kjøp blomster til begravelsen</h1>
            <p>En siste hilsen med blomster kan bety mer enn tusen ord.<p>
            <p>Få blomster sendt direkte til begravelsen eller til hjemmet</p>
            <button class="btn-main btn-banner">Bestill nå</button>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/kontakt.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
    </div>
  </div>
</div>

app/views/pages/om_oss.html.erb
<div class="container-fluid  main-hero">
  <div class="row full-height om-oss">
    <div class="col main-col mid-c full-height">
      <div class="box text-center">
        <h1>Om oss</h1>
        <p>Vi er totalleverandør innen begravelse</p>
        <p>Hos oss vil du bli tatt vare på med respekt og verdighet</p>
        <button class="btn">Se begravelse</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/seremoni.html.erb
<div class="container hello">
  <h1>Dette er seremoni siden</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

app/views/pages/til_begravelsen.html.erb
<div class="container-fluid banner-background">
  <div class="container-fluid  main-hero">
    <div class="row full-height til-begravelsen">
      <div class="col main-col mid-c full-height">
        <div class="box">
          <h1>Til begravelsen</h1>
          <p>Vi er totalleverandør innen begravelse</p>
          <p>Hos oss vil du bli tatt vare på med respekt og verdighet</p>
          <button class="btn"> <a href="#begravelse">Les mer</a></button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid" id="begravelse">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="page-box">
          <h5>Seremoni</h5>
          <div class="info-img">
            <%= image_tag 'church.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="page-box">
          <h5>Blomster</h5>
          <div class="info-img">
            <%= image_tag 'boquet.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="page-box">
          <h5>Kister</h5>
          <div class="info-img">
            <%= image_tag 'kiste.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="page-box">
          <h5>Urner</h5>
          <div class="info-img">
            <%= image_tag 'urner.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="page-box">
          <h5>Musikk</h5>
          <div class="info-img">
            <%= image_tag 'piano.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main">Les mer</button>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="page-box">
          <h5>Transport</h5>
          <div class="info-img">
            <%= image_tag 'chevrolet.jpg', class: 'img-fluid' %>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <button class="btn-main">Les mer</button>
        </div>
      </div>


    </div>   <!-- row -->
  </div>  <!-- container -->
</div>  <!-- container-fluid -->

app/views/pages/tjenester.html.erb
Tjenester