config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'ved_dodsfall' => 'pages#ved_dodsfall'
  get 'til_begravelsen' => 'pages#begravelse'
  get 'etter_begravelsen' => 'pages#etter_begravelsen'
  get 'seremoni' => 'pages#seremoni'
  get 'om_oss' => 'pages#om_oss'
  get 'dashboard/index'
  root 'pages#homepage'

  resources :posts
  resources :admin

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/models/obit.rb
class Obit < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :tributes

end

app/models/page.rb
class Page < ApplicationRecord
  has_many :sections
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :page
end

app/models/tribute.rb
class Tribute < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :obit
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

  def show
  end

  def destroy
  redirect_to pages_begravelse_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.save
    puts @post.inspect
    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, :notice => "Innlegget har blitt slettet"
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to posts_path, :notice => "Innlegget ditt har blitt oppdatert"
    else
      render "edit"
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/begravelse_helper.rb
module BegravelseHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hjelp_helper.rb
module HjelpHelper
end

app/helpers/obits_helper.rb
module ObitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tributes_helper.rb
module TributesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/edit.html.erb
<br />
<br />
<div class="container">
  <div class="row">
    <div class="col-8 offset-2 post-form">
      <h1>Rediger innlegg</h1>
      <%= form_for @post do |f| %>
        <p>
        <%= f.label :tittel %><br />
        <%= f.text_field :title, class: "form-field form-title" %>
        </p>

        <p>
          <%= f.label :innlegg %><br />
          <%= f.text_area :body, class: "tinymce form-field form-text" %>
        </p>
        <p>
          <%= f.label :last_opp_bilde %><br>
          <%= f.file_field :image %>
        </p>
        <%= f.submit 'Lagre innlegg', data: {:confirm => "Er du sikker at du vil oppdatere innlegget?"}, :class => 'btn btn-primary btn-sm btn-post' %>
      <% end %>
    </div>
  </div>
</div>
<%= tinymce %>

app/views/posts/index.html.erb
<br />
<br />
<div class="container posts">
  <div class="row">
    <div class="col-8 offset-2">
      <% @posts.each do |post|%>
        <br />
        <h1><%= link_to post.title, post_path(post) %></h1>
        <%= image_tag post.image, class: 'img-fluid' %>
        <br />
        <p>
          <%= simple_format post.content %>
        </p>
        <br />
        <%= link_to 'Les mer', post_path(post), class: 'btn btn-sm btn-primary btn-post' %>
        <% if admin_signed_in? %>
          <%= link_to "Rediger", edit_post_path(post), class: 'btn btn-sm btn-primary btn-post' %>
          <%= link_to "Slett", post, :method => :delete, data: {:confirm => "Er du sikker at du vil slette innlegget #{post.title}?"}, class: 'btn btn-sm btn-primary btn-post' %>
        <% end %>
        <br />
        <br />
      <% end %>
    </div>
  </div>

  <br />
  <% if admin_signed_in? %>
  <%= link_to 'Nytt innlegg', new_post_path , class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/new.html.erb
<br />
<br />
<br />
<div class="container">
  <div class="row">
    <div class="col-10 offset-1 post-form">
      <h1>Nytt innlegg</h1>
      <%= form_for :post, url: posts_path do |f| %>
        <p>
        <%= f.label :tittel %><br />
        <%= f.text_field :title, class: 'form-field form-title' %>
        </p>
        <p>
          <%= f.label :innlegg %><br />
          <%= f.text_area :content, class: 'tinymce form-field form-text' %>
        </p>
        <p>
        <%= f.label :last_opp_bilde %><br>
        <%= f.file_field :image %>
        </p>
        <%= f.submit 'Lagre innlegg', :class => 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<%= tinymce %>

app/views/posts/show.html.erb
<br />
<br />
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h1 class="title">
        <%= @post.title %>
      </h1>
      <div class="">
        <%= image_tag @post.image, class: 'img-fluid' %>
      </div>
      <p class="date">
        submitted <%= time_ago_in_words(@post.created_at) %> Ago
      </p>
      <div class="body">
        <%= simple_format @post.content %>
      </div>
    </div>
  </div>
</div>